// Standard PDF font encodings (ISO 32000-2 Annex D / PDF Reference Annex D).
//
// Each encoding maps a 1-byte code (0..255) to a glyph name. Combined with
// the AGL (GlyphList.ts) this gives byte → Unicode for simple fonts.
//
// ASCII printable (0x20..0x7E) is identical across StandardEncoding,
// MacRomanEncoding, and WinAnsiEncoding, so we share that base table.
// The encodings differ in the 0x80..0xFF range (and a few control-char
// positions); each encoding declares only its overrides relative to the
// shared ASCII base.

/** Bytes 0x20..0x7E — identical in all three Latin encodings. */
const ASCII_GLYPHS: Readonly<Record<number, string>> = Object.freeze({
  0x20: 'space',
  0x21: 'exclam',
  0x22: 'quotedbl',
  0x23: 'numbersign',
  0x24: 'dollar',
  0x25: 'percent',
  0x26: 'ampersand',
  0x27: 'quotesingle',
  0x28: 'parenleft',
  0x29: 'parenright',
  0x2a: 'asterisk',
  0x2b: 'plus',
  0x2c: 'comma',
  0x2d: 'hyphen',
  0x2e: 'period',
  0x2f: 'slash',
  0x30: 'zero',
  0x31: 'one',
  0x32: 'two',
  0x33: 'three',
  0x34: 'four',
  0x35: 'five',
  0x36: 'six',
  0x37: 'seven',
  0x38: 'eight',
  0x39: 'nine',
  0x3a: 'colon',
  0x3b: 'semicolon',
  0x3c: 'less',
  0x3d: 'equal',
  0x3e: 'greater',
  0x3f: 'question',
  0x40: 'at',
  0x41: 'A',
  0x42: 'B',
  0x43: 'C',
  0x44: 'D',
  0x45: 'E',
  0x46: 'F',
  0x47: 'G',
  0x48: 'H',
  0x49: 'I',
  0x4a: 'J',
  0x4b: 'K',
  0x4c: 'L',
  0x4d: 'M',
  0x4e: 'N',
  0x4f: 'O',
  0x50: 'P',
  0x51: 'Q',
  0x52: 'R',
  0x53: 'S',
  0x54: 'T',
  0x55: 'U',
  0x56: 'V',
  0x57: 'W',
  0x58: 'X',
  0x59: 'Y',
  0x5a: 'Z',
  0x5b: 'bracketleft',
  0x5c: 'backslash',
  0x5d: 'bracketright',
  0x5e: 'asciicircum',
  0x5f: 'underscore',
  0x60: 'grave',
  0x61: 'a',
  0x62: 'b',
  0x63: 'c',
  0x64: 'd',
  0x65: 'e',
  0x66: 'f',
  0x67: 'g',
  0x68: 'h',
  0x69: 'i',
  0x6a: 'j',
  0x6b: 'k',
  0x6c: 'l',
  0x6d: 'm',
  0x6e: 'n',
  0x6f: 'o',
  0x70: 'p',
  0x71: 'q',
  0x72: 'r',
  0x73: 's',
  0x74: 't',
  0x75: 'u',
  0x76: 'v',
  0x77: 'w',
  0x78: 'x',
  0x79: 'y',
  0x7a: 'z',
  0x7b: 'braceleft',
  0x7c: 'bar',
  0x7d: 'braceright',
  0x7e: 'asciitilde',
});

/** WinAnsi (CP1252-flavored) — overrides for 0x80..0xFF. */
const WIN_ANSI_OVERRIDES: Readonly<Record<number, string>> = Object.freeze({
  // 0x80 block — ANSI/Windows extensions
  0x80: 'Euro',
  0x82: 'quotesinglbase',
  0x83: 'florin',
  0x84: 'quotedblbase',
  0x85: 'ellipsis',
  0x86: 'dagger',
  0x87: 'daggerdbl',
  0x88: 'circumflex',
  0x89: 'perthousand',
  0x8a: 'Scaron',
  0x8b: 'guilsinglleft',
  0x8c: 'OE',
  0x8e: 'Zcaron',
  0x91: 'quoteleft',
  0x92: 'quoteright',
  0x93: 'quotedblleft',
  0x94: 'quotedblright',
  0x95: 'bullet',
  0x96: 'endash',
  0x97: 'emdash',
  0x98: 'tilde',
  0x99: 'trademark',
  0x9a: 'scaron',
  0x9b: 'guilsinglright',
  0x9c: 'oe',
  0x9e: 'zcaron',
  0x9f: 'Ydieresis',

  // 0xA0 block — Latin-1 supplement (1:1 with Unicode here)
  0xa0: 'space',
  0xa1: 'exclamdown',
  0xa2: 'cent',
  0xa3: 'sterling',
  0xa4: 'currency',
  0xa5: 'yen',
  0xa6: 'brokenbar',
  0xa7: 'section',
  0xa8: 'dieresis',
  0xa9: 'copyright',
  0xaa: 'ordfeminine',
  0xab: 'guillemotleft',
  0xac: 'logicalnot',
  0xad: 'hyphen',
  0xae: 'registered',
  0xaf: 'macron',
  0xb0: 'degree',
  0xb1: 'plusminus',
  0xb2: 'twosuperior',
  0xb3: 'threesuperior',
  0xb4: 'acute',
  0xb5: 'mu',
  0xb6: 'paragraph',
  0xb7: 'periodcentered',
  0xb8: 'cedilla',
  0xb9: 'onesuperior',
  0xba: 'ordmasculine',
  0xbb: 'guillemotright',
  0xbc: 'onequarter',
  0xbd: 'onehalf',
  0xbe: 'threequarters',
  0xbf: 'questiondown',
  0xc0: 'Agrave',
  0xc1: 'Aacute',
  0xc2: 'Acircumflex',
  0xc3: 'Atilde',
  0xc4: 'Adieresis',
  0xc5: 'Aring',
  0xc6: 'AE',
  0xc7: 'Ccedilla',
  0xc8: 'Egrave',
  0xc9: 'Eacute',
  0xca: 'Ecircumflex',
  0xcb: 'Edieresis',
  0xcc: 'Igrave',
  0xcd: 'Iacute',
  0xce: 'Icircumflex',
  0xcf: 'Idieresis',
  0xd0: 'Eth',
  0xd1: 'Ntilde',
  0xd2: 'Ograve',
  0xd3: 'Oacute',
  0xd4: 'Ocircumflex',
  0xd5: 'Otilde',
  0xd6: 'Odieresis',
  0xd7: 'multiply',
  0xd8: 'Oslash',
  0xd9: 'Ugrave',
  0xda: 'Uacute',
  0xdb: 'Ucircumflex',
  0xdc: 'Udieresis',
  0xdd: 'Yacute',
  0xde: 'Thorn',
  0xdf: 'germandbls',
  0xe0: 'agrave',
  0xe1: 'aacute',
  0xe2: 'acircumflex',
  0xe3: 'atilde',
  0xe4: 'adieresis',
  0xe5: 'aring',
  0xe6: 'ae',
  0xe7: 'ccedilla',
  0xe8: 'egrave',
  0xe9: 'eacute',
  0xea: 'ecircumflex',
  0xeb: 'edieresis',
  0xec: 'igrave',
  0xed: 'iacute',
  0xee: 'icircumflex',
  0xef: 'idieresis',
  0xf0: 'eth',
  0xf1: 'ntilde',
  0xf2: 'ograve',
  0xf3: 'oacute',
  0xf4: 'ocircumflex',
  0xf5: 'otilde',
  0xf6: 'odieresis',
  0xf7: 'divide',
  0xf8: 'oslash',
  0xf9: 'ugrave',
  0xfa: 'uacute',
  0xfb: 'ucircumflex',
  0xfc: 'udieresis',
  0xfd: 'yacute',
  0xfe: 'thorn',
  0xff: 'ydieresis',
});

/** MacRoman — Apple's classic 8-bit encoding. Overrides for 0x80..0xFF. */
const MAC_ROMAN_OVERRIDES: Readonly<Record<number, string>> = Object.freeze({
  0x80: 'Adieresis',
  0x81: 'Aring',
  0x82: 'Ccedilla',
  0x83: 'Eacute',
  0x84: 'Ntilde',
  0x85: 'Odieresis',
  0x86: 'Udieresis',
  0x87: 'aacute',
  0x88: 'agrave',
  0x89: 'acircumflex',
  0x8a: 'adieresis',
  0x8b: 'atilde',
  0x8c: 'aring',
  0x8d: 'ccedilla',
  0x8e: 'eacute',
  0x8f: 'egrave',
  0x90: 'ecircumflex',
  0x91: 'edieresis',
  0x92: 'iacute',
  0x93: 'igrave',
  0x94: 'icircumflex',
  0x95: 'idieresis',
  0x96: 'ntilde',
  0x97: 'oacute',
  0x98: 'ograve',
  0x99: 'ocircumflex',
  0x9a: 'odieresis',
  0x9b: 'otilde',
  0x9c: 'uacute',
  0x9d: 'ugrave',
  0x9e: 'ucircumflex',
  0x9f: 'udieresis',
  0xa0: 'dagger',
  0xa1: 'degree',
  0xa2: 'cent',
  0xa3: 'sterling',
  0xa4: 'section',
  0xa5: 'bullet',
  0xa6: 'paragraph',
  0xa7: 'germandbls',
  0xa8: 'registered',
  0xa9: 'copyright',
  0xaa: 'trademark',
  0xab: 'acute',
  0xac: 'dieresis',
  0xad: 'notequal',
  0xae: 'AE',
  0xaf: 'Oslash',
  0xb0: 'infinity',
  0xb1: 'plusminus',
  0xb2: 'lessequal',
  0xb3: 'greaterequal',
  0xb4: 'yen',
  0xb5: 'mu',
  0xb6: 'partialdiff',
  0xb8: 'product', // not in our AGL; will report missing
  0xb9: 'pi',
  0xba: 'integral',
  0xbb: 'ordfeminine',
  0xbc: 'ordmasculine',
  0xbd: 'Omega',
  0xbe: 'ae',
  0xbf: 'oslash',
  0xc0: 'questiondown',
  0xc1: 'exclamdown',
  0xc2: 'logicalnot',
  0xc3: 'radical',
  0xc4: 'florin',
  0xc5: 'approxequal',
  0xc7: 'guillemotleft',
  0xc8: 'guillemotright',
  0xc9: 'ellipsis',
  0xca: 'space', // nbspace alternative
  0xcb: 'Agrave',
  0xcc: 'Atilde',
  0xcd: 'Otilde',
  0xce: 'OE',
  0xcf: 'oe',
  0xd0: 'endash',
  0xd1: 'emdash',
  0xd2: 'quotedblleft',
  0xd3: 'quotedblright',
  0xd4: 'quoteleft',
  0xd5: 'quoteright',
  0xd6: 'divide',
  0xd8: 'ydieresis',
  0xd9: 'Ydieresis',
  0xda: 'fraction',
  0xdb: 'currency',
  0xdc: 'guilsinglleft',
  0xdd: 'guilsinglright',
  0xde: 'fi',
  0xdf: 'fl',
  0xe0: 'daggerdbl',
  0xe1: 'periodcentered',
  0xe2: 'quotesinglbase',
  0xe3: 'quotedblbase',
  0xe4: 'perthousand',
  0xe5: 'Acircumflex',
  0xe6: 'Ecircumflex',
  0xe7: 'Aacute',
  0xe8: 'Edieresis',
  0xe9: 'Egrave',
  0xea: 'Iacute',
  0xeb: 'Icircumflex',
  0xec: 'Idieresis',
  0xed: 'Igrave',
  0xee: 'Oacute',
  0xef: 'Ocircumflex',
  0xf1: 'Ograve',
  0xf2: 'Uacute',
  0xf3: 'Ucircumflex',
  0xf4: 'Ugrave',
});

/**
 * Adobe StandardEncoding — the default encoding for Type1 fonts that don't
 * declare their own. Only the ASCII range and a few special punctuation are
 * universally defined; anything beyond that is implementation-specific.
 */
const STANDARD_OVERRIDES: Readonly<Record<number, string>> = Object.freeze({
  0xa1: 'exclamdown',
  0xa2: 'cent',
  0xa3: 'sterling',
  0xa4: 'fraction',
  0xa5: 'yen',
  0xa6: 'florin',
  0xa7: 'section',
  0xa8: 'currency',
  0xa9: 'quotesingle',
  0xaa: 'quotedblleft',
  0xab: 'guillemotleft',
  0xac: 'guilsinglleft',
  0xad: 'guilsinglright',
  0xae: 'fi',
  0xaf: 'fl',
  0xb1: 'endash',
  0xb2: 'dagger',
  0xb3: 'daggerdbl',
  0xb4: 'periodcentered',
  0xb6: 'paragraph',
  0xb7: 'bullet',
  0xb8: 'quotesinglbase',
  0xb9: 'quotedblbase',
  0xba: 'quotedblright',
  0xbb: 'guillemotright',
  0xbc: 'ellipsis',
  0xbd: 'perthousand',
  0xbf: 'questiondown',
  0xc1: 'grave',
  0xc2: 'acute',
  0xc3: 'circumflex',
  0xc4: 'tilde',
  0xc5: 'macron',
  0xc8: 'dieresis',
  0xca: 'ring',
  0xcb: 'cedilla',
  0xcd: 'hungarumlaut',
  0xce: 'ogonek',
  0xcf: 'caron',
  0xe1: 'AE',
  0xe3: 'ordfeminine',
  0xe8: 'Lslash',
  0xe9: 'Oslash',
  0xea: 'OE',
  0xeb: 'ordmasculine',
  0xf1: 'ae',
  0xf5: 'dotlessi',
  0xf8: 'lslash',
  0xf9: 'oslash',
  0xfa: 'oe',
  0xfb: 'germandbls',
});

/** Names of the standard encodings recognized by `getStandardEncoding`. */
export type StandardEncodingName =
  | 'WinAnsiEncoding'
  | 'MacRomanEncoding'
  | 'MacExpertEncoding'
  | 'StandardEncoding';

/**
 * Build the byte → glyph-name map for a named standard encoding by merging
 * ASCII_GLYPHS with the encoding's overrides.
 */
export function getStandardEncoding(name: StandardEncodingName): Readonly<Record<number, string>> {
  switch (name) {
    case 'WinAnsiEncoding':
      return { ...ASCII_GLYPHS, ...WIN_ANSI_OVERRIDES };
    case 'MacRomanEncoding':
      return { ...ASCII_GLYPHS, ...MAC_ROMAN_OVERRIDES };
    case 'StandardEncoding':
      return { ...ASCII_GLYPHS, ...STANDARD_OVERRIDES };
    case 'MacExpertEncoding':
      // MacExpert is rarely used (specialized typographic glyphs). We return
      // the ASCII base; callers will report missing glyphs for upper-range
      // bytes and the policy layer falls back to redact-and-reemit.
      return { ...ASCII_GLYPHS };
  }
}

/** True if `name` is a standard PDF encoding name. */
export function isStandardEncodingName(name: string): name is StandardEncodingName {
  return (
    name === 'WinAnsiEncoding' ||
    name === 'MacRomanEncoding' ||
    name === 'MacExpertEncoding' ||
    name === 'StandardEncoding'
  );
}
